services:
  - type: web
    name: rahl-quantum
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: OWNER_NUMBER
        value: "254112399557" # change to your WhatsApp number
